##https://github.com/bitnami/charts/tree/master/bitnami/external-dns/#installing-the-chart
policy: upsert-only
sources:
- ingress
- service
provider: aws
txtOwnerId: ${txt_owner_id}
registry: txt
aws:
  zoneType: public
  region: ${external_dns_region}
  assumeRoleArn: arn:aws:iam::${account_id}:role/{external_dns_role_name}